### ISSUE TITLE
Azure China Cloud is not supported

### ISSUE THREAD

**Issue by RomRider** [pivotal-cf/azure-blobstore-resource#5] opened 2018-11-05 09:33 UTC
Hi there,

We're trying to use this resource with Azure China and it fails to check the resource because the base URL of the blobstore is hardcoded and by default is `blob.core.windows.net`.
In Azure China, this URL should be `blob.core.windows.cn`.

There should be a way to provide an input to define which Azure you want to use (defaulting to AzureCloud) like in this resource: https://github.com/pivotal-cloudops/azure-blobstore-concourse-resource

The error you'd get by using this resource against Azure China Cloud is:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
2018/11/05 08:21:26 failed to get latest version: Get https://BLOBSTORENAME.blob.core.windows.net/XXXXXXXX?comp=list&include=snapshots&prefix=FILE.NAME&restype=container: dial tcp: lookup BLOBSTORENAME.blob.core.windows.net on 168.63.129.16:53: no such host
```

Thanks for your help.
CC: @lakshmantgld @keliangneu

**Comment by christianang** [comment] 2018-11-08 02:13
Thanks for bringing this up. I've added a new `base_url` param in the source configuration. This should be set to `core.windows.cn` in your case.

E.g:

```
resources:
  - name: terraform-state
    type: azure-blobstore
    source:
      base_url: core.windows.cn
      storage_account_name: {{storage_account_name}}
      storage_account_key: {{storage_account_key}}
      container: {{container}}
      versioned_file: terraform.tfstate
```

If not set it will default to the normal Azure Public Cloud: `core.windows.net`

**Comment by keliangneu** [comment] 2018-11-08 02:37
Hello Christian,

 

Thank you, I added the base_url to the source, but it seems not work. 

resource script '/opt/resource/check []' failed: exit status 1

 

stderr:

2018/11/08 02:34:47 failed to get latest version: Get https://cnkplatsadev.blob.core.windows.net/terraform?comp=list&include=snapshots&prefix=terraform.tfstate&restype=container: dial tcp: lookup cnkplatsadev.blob.core.windows.net on 168.63.129.16:53: no such host

**Comment by keliangneu** [comment] 2018-11-08 03:18
It's working now as expected, thank you for the heads up.

**Comment by keliangneu** [comment] 2018-11-08 03:32
Dear support the issue is now fixed , thank you so much.

**Comment by RomRider** [comment] 2018-11-08 15:29
Awesome, thank you @christianang !

**Closed** 2018-11-14 00:10 UTC
Labels: unscheduled
